In [1]:
######## SQL connection ############

import pypyodbc # pip install pypyodbc
import pandas as pd # pip install pandas

SERVER_NAME = 'DESKTOP-H2M6ONO'
DATABASE_NAME = 'test'

conn = pypyodbc.connect("""
    Driver={{SQL Server Native Client 11.0}};
    Server={0};
    Database={1};
    Trusted_Connection=yes;""".format(SERVER_NAME, DATABASE_NAME)
)

sql_query1 = """
SELECT * FROM organization_provider WITH (NoLock)
"""

# With Headers
organization_provider = pd.read_sql(sql_query1, conn)


sql_query2 = """
SELECT * FROM Encounters_medical_details WITH (NoLock)
"""

# With Headers
Encounters_medical_details = pd.read_sql(sql_query2, conn)

sql_query3 = """
SELECT * FROM patients_filtered WITH (NoLock)
"""

# With Headers
patients_filtered = pd.read_sql(sql_query3, conn)

In [2]:
organization_provider

,organization_id,provider_id,organization_name,provider_name,provider_gender,provider_speciality,organization_city,provider_city,organization_state,provider_state,organization_utilization,provider_utilization
0,07c785a5-09ba-42e7-bd0d-526ea15ea991,7a31287b-3c1f-4f00-ad1f-0d408ff03c84,ORLANDO HEALTH,Lowell343 Bergnaum523,M,GENERAL PRACTICE,ORLANDO,ORLANDO,FL,FL,903,903
1,6873f7b3-4af0-41cd-9520-cacd6aa45fcf,1d9d36a6-824a-4ab8-ac3d-697ac8c5b641,UNIVERSITY OF MIAMI HOSPITAL,Agustín529 Casillas702,M,GENERAL PRACTICE,MIAMI,MIAMI,FL,FL,1351,1351
2,c58a830c-d3a9-4f9f-84b4-6997c6709fed,d85414c6-6b9d-4409-a84b-2e53a91f4ff5,LEE MEMORIAL HOSPITAL,Ricky354 Kihn564,M,GENERAL PRACTICE,FORT MYERS,FORT MYERS,FL,FL,329,329
3,1a89c332-c8e4-4169-a7bd-d96f3a7f53b7,21045838-3d2a-45f7-a2b7-58b71e631e80,HALIFAX HEALTH MEDICAL CENTER,Bessie423 Altenwerth646,F,GENERAL PRACTICE,DAYTONA BEACH,DAYTONA BEACH,FL,FL,1320,1320
4,440ee2c4-cf8e-4d6b-8d2c-81bfa43dc54b,44f6beb7-9fab-4dc8-898d-06559f637c63,BAY MEDICAL CENTER SACRED HEART HEALTH SYSTEM,Mandy775 Dooley940,F,GENERAL PRACTICE,PANAMA CITY,PANAMA CITY,FL,FL,115,115
...,...,...,...,...,...,...,...,...,...,...,...,...
84,8dc11b71-ad28-4fa9-b0d2-5c6c64922c78,b6020302-6e60-4822-8b71-a4a6fdafd445,MARATHON HEALTH CENTER,Waldo53 Prosacco716,M,GENERAL PRACTICE,MARATHON,MARATHON,FL,FL,1,1
85,28430922-d60f-4869-a8c5-3e05d83d74d7,49a25cd3-fbe0-4808-a689-bbeecbf04c1e,BAPTIST MEDICAL PLAZA AT MIAMI LAKES,Leo278 Sauer652,F,GENERAL PRACTICE,MIAMI,MIAMI,FL,FL,13,13
86,f2c0879a-b622-48dc-9a02-e52a980dca07,9af48451-fcb9-4316-848c-620c96e3f511,FIRST CHOICE URGENT CARE,Kelvin159 Ritchie586,M,GENERAL PRACTICE,CHULUOTA,CHULUOTA,FL,FL,15,15
87,f6c5fd10-beda-4420-8dca-e28cc495e683,7083f108-ea01-4097-a64c-2b14960bae39,CONCENTRA URGENT CARE MEDICAL CENTER - WEST PA...,Mauricio81 Christiansen251,M,GENERAL PRACTICE,WEST PALM BEACH,WEST PALM BEACH,FL,FL,4,4
88,f14f97ac-f78f-432d-bd85-e79d003c606d,6d4ef70d-8f56-4e13-93be-a8153fceda76,DOCTORS WALK-IN CLINIC - NORTHSIDE,Miles206 Hills818,M,GENERAL PRACTICE,TAMPA,TAMPA,FL,FL,53,53

In [3]:
organization_provider.to_csv(r'C:\Users\91993\Documents\Florida\Data\Final_tables\organization_provider.csv', index=None, sep=',', mode='a')

In [31]:
Encounters_medical_details.to_csv(r'C:\Users\91993\Documents\Florida\Data\Final_tables\Encounters_medical_details.csv', index=None, sep=',', mode='a')

In [32]:
patients_filtered.to_csv(r'C:\Users\91993\Documents\Florida\Data\Final_tables\patients_filtered.csv', index=None, sep=',', mode='a')

In [15]:
######## My Sql Connection ############### 
#import mysql
from mysql.connector import (connection)

cnx = connection.MySQLConnection(user='root', password='root',
                                 host='localhost',
                                 database='medical_data',
                                auth_plugin='mysql_native_password')

sql_query1 = 'Select * from encounters';

encounters = pd.read_sql(sql_query1, cnx)

cnx.close()

In [16]:
encounters

,ID,START,STOP,PATIENT,PROVIDER,ENCOUNTERCLASS,CODE,DESCRIPTION,COST,REASONCODE,REASONDESCRIPTION
0,0001d46a-e330-4f50-bf70-05d2dc882785,1990-03-09 11:47:18,1990-03-09 13:00:18,df649e27-4b8b-4b1e-80bc-bff59b1cd78b,5a32534d-c669-4992-b150-02730c16d8fc,ambulatory,371883000,Outpatient procedure,116.43,,
1,00025347-8ad2-43ef-80ca-90c88b8e124d,1988-10-28 11:47:18,1988-10-28 13:17:18,df649e27-4b8b-4b1e-80bc-bff59b1cd78b,5a32534d-c669-4992-b150-02730c16d8fc,emergency,183460006,Obstetric emergency hospital admission,116.43,72892002,Normal pregnancy
2,000b3b07-eaca-43cb-9e23-1e0e48290c0b,1976-05-16 08:46:39,1976-05-16 10:16:39,acc7fa1c-24dc-4aa7-92a8-fe4f015f0c47,07c785a5-09ba-42e7-bd0d-526ea15ea991,emergency,183460006,Obstetric emergency hospital admission,116.43,72892002,Normal pregnancy
3,000ecbad-fc09-459d-841d-0aea09d70430,1996-05-23 13:20:16,1996-05-23 13:50:16,6817429c-208f-4f32-b860-0fa053fae5b6,6873f7b3-4af0-41cd-9520-cacd6aa45fcf,wellness,185349003,Encounter for check up (procedure),116.43,,
4,0010bd3b-ff85-497d-917a-056e88b8e1f1,2003-02-21 14:51:22,2003-02-21 15:06:22,9d245cc6-e9c6-44df-8211-2e9e5fbbddc0,6769271e-e95e-46b1-91fe-e7625fe6dca2,outpatient,698314001,Consultation for treatment,116.43,,
...,...,...,...,...,...,...,...,...,...,...,...
14260,ffecb507-e44b-4834-92a7-69a453475a05,2015-03-26 13:11:22,2015-03-26 15:26:22,b6e95230-5546-42d9-b99f-b8dc6e57d007,73d8aa81-4792-4fcc-95f9-c462213c40b2,ambulatory,185347001,Encounter for problem (procedure),116.43,431856006,Chronic kidney disease stage 2 (disorder)
14261,ffeec5ea-c12b-47ee-9115-5e0782ea3642,2014-02-05 07:11:26,2014-02-05 07:41:26,42daea0b-6b0a-4638-8aee-e69e230e5cf1,bbed77c8-b8f6-4a16-a2e7-58d30a46a79a,wellness,185349003,Encounter for check up (procedure),116.43,,
14262,fff118f6-7907-43ea-8881-306c741ae70b,2015-08-17 19:44:17,2015-08-17 19:59:17,d78f492b-0189-41e7-bb53-3c827e9bccff,f26bcfd1-8a23-4c3a-9429-5aa7affea78f,urgentcare,371883000,Outpatient procedure (procedure),116.43,,
14263,fff796ca-aad6-4a5b-a55f-d23509dbd10a,2015-10-06 11:33:57,2015-10-06 11:48:57,5c81f139-385c-47d5-a205-35a1ce369808,74d5931c-3e13-4ab5-a822-0a97e23c12e9,wellness,185349003,Encounter for check up (procedure),116.43,,
14264,fff9b1a5-a0dc-4a6f-b295-927578ee3080,2003-06-24 19:38:31,2003-06-24 19:53:31,f8d78433-3c20-4e81-b778-0eafea4a999c,c58a830c-d3a9-4f9f-84b4-6997c6709fed,outpatient,185347001,Encounter for problem (procedure),116.43,,

In [17]:
encounters.to_csv(r'C:\Users\91993\Documents\Florida\Data\Final_tables\encounters.csv', index=None, sep=',', mode='a')